# SPDX-FileCopyrightText: © 2026 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

# Configuration file for `reuse`, a tool for compliance with the REUSE spec.
# See https://reuse.software/spec for more information.

version = 1

# Uncopyrightable files
[[annotations]]
path = [
    ".gitignore",
    "cspell.json",
    "go.mod",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Uncommentable files
[[annotations]]
path = [
    "internal/generate/templates/*",
]
precedence = "override"
SPDX-FileCopyrightText = "© hazzuk"
SPDX-License-Identifier = "AGPL-3.0-only"
